### ISSUE TITLE
Visual glitch in bottom left menu

### ISSUE THREAD

**Issue by dullahan8** [ajbogh/OWAFull#5]
I installed this just today from the Chrome Web Store and I am getting this strange glitch in the bottom left of my mailbox.

![image](https://user-images.githubusercontent.com/7637030/27620230-f709c8ca-5b7c-11e7-98c4-901127cda129.png)

Windows 10, Chrome Version 58.0.3029.110 (64-bit)

**Comment by ajbogh** [comment]
Can you respond with the OWA version if you know it?

I've never seen this before. It's hard to understand what's going on without seeing what it looks like normally. Can you include a picture using Firefox or IE/Edge so we can see what it looks like normally? The extension shouldn't run inside the mailbox, only on the login screen, so I'm unsure of how it could cause a glitch like this.

If you feel up to trying to fix it, I would really appreciate the help.

**Comment by ajbogh** [comment]
@dullahan8, please feel free to submit a PR with a fix or close this ticket if it's no longer relevant.

**Comment by dullahan8** [comment]
Yes sorry. I went on vacation afterwards and totally forgot about this. I'm not using it at the moment so I'll close this ticket.
